import Foundation

/// The ⓘ text of every check (M1-00, B07): what it proves, numbered steps, and where it
/// happens (for the To do list). "Expected" comes from the check itself.
struct CheckGuide {
    enum Place: String, CaseIterable {
        case noScooter = "No scooter"
        case scooterHome = "Scooter at home"
        case ride = "On a ride"
        case passive = "Passive"
    }

    let proves: String
    let steps: [String]
    let place: Place

    static func of(_ id: String) -> CheckGuide {
        all[id] ?? CheckGuide(proves: "—", steps: ["See the check's description."], place: .noScooter)
    }

    static let all: [String: CheckGuide] = [
        "h2": CheckGuide(proves: "Notification sounds are on, so the Kick-off chime can play (B10).",
                         steps: ["Developer → Permissions → step 1 (allow notifications with sounds).",
                                 "If Sounds still isn't on: step 6 → iPhone Settings → Notifications → CorckieApp → Sounds ON.",
                                 "Come back: the check updates by itself."], place: .noScooter),
        "h1": CheckGuide(proves: "The app has every permission v1 needs to record rides with the phone in your pocket.",
                         steps: ["Developer → Permissions.", "Do steps 1–6 top to bottom: notifications (with sounds), location While Using, then Always, motion, Bluetooth, sounds.",
                                 "If a prompt doesn't appear, the button opens iPhone Settings → CorckieApp.",
                                 "Come back to the app: the check updates by itself."], place: .noScooter),
        "a1": CheckGuide(proves: "The cloud-built app installs and starts on your iPhone.",
                         steps: ["Install the .ipa with SideStore.", "Open CorckieApp once."], place: .noScooter),
        "a2": CheckGuide(proves: "The Home Screen shows the right name and the scooter icon.",
                         steps: ["Go to the Home Screen.", "Look at the icon and the name under it.", "Tap Pass or Fail."], place: .noScooter),
        "a7": CheckGuide(proves: "\"v1\" is visible inside the app on every screen.",
                         steps: ["Visit each tab, Settings, Developer, Checks and two tool screens.",
                                 "Each time look at the bottom-right corner.", "Tap Pass or Fail."], place: .noScooter),
        "a3": CheckGuide(proves: "The app keeps its permanent ID, so updates keep your data.",
                         steps: ["Nothing to do: it marks itself at every launch."], place: .noScooter),
        "a4": CheckGuide(proves: "Installing a new build over the old one keeps all data.",
                         steps: ["In SideStore, install the new .ipa over the existing app (don't delete the app).",
                                 "Open CorckieApp: the check marks itself."], place: .noScooter),
        "a5": CheckGuide(proves: "SideStore renews the 7-day signing by itself.",
                         steps: ["Don't tap Refresh in SideStore for a few days.",
                                 "Before day 7, open SideStore: has the expiry date moved on by itself?", "Tap Pass or Fail."], place: .passive),
        "a6": CheckGuide(proves: "The database opened and is up to date (data versioning).",
                         steps: ["Nothing to do: it marks itself at every launch."], place: .noScooter),
        "b1": CheckGuide(proves: "The app finds and connects to the scooter.",
                         steps: ["Switch the scooter on.", "Developer → Scooter.", "Wait about 10 s."], place: .scooterHome),
        "b2": CheckGuide(proves: "The scooter's data is decoded into sensible numbers.",
                         steps: ["Stay on Developer → Scooter with the scooter on for ~10 s."], place: .scooterHome),
        "b3": CheckGuide(proves: "The scooter's firmware is the one the decoder was built for.",
                         steps: ["Read automatically when the scooter connects."], place: .scooterHome),
        "b4": CheckGuide(proves: "The app only reads from the scooter: it never sends anything.",
                         steps: ["Read automatically when the scooter connects."], place: .scooterHome),
        "b5": CheckGuide(proves: "Whether the scooter reports a lock state.",
                         steps: ["Developer → Scooter → Lock: Record.", "Lock and unlock 3 times, ~5 s apart.",
                                 "Stop and check (or tap \"No lock on this scooter\")."], place: .scooterHome),
        "b8": CheckGuide(proves: "The Bluetooth link holds for 4 minutes with nothing happening (B04). The scooter switches itself off after ~5 min standing, so the test is 4 min.",
                         steps: ["iPhone Settings → Display & Brightness → Auto-Lock → Never (set it back afterwards).",
                                 "Scooter on, standing still.", "Developer → Scooter → Start 4-min test.",
                                 "Keep the phone UNLOCKED on this screen for the full 4 minutes: don't switch apps or lock it.",
                                 "The result shows at 4:00."], place: .scooterHome),
        "b9": CheckGuide(proves: "When the scooter goes out of range, the app reconnects by itself when you come back.",
                         steps: ["Scooter on. Developer → Scooter → Arm range test.", "Lock the phone.",
                                 "Walk 30–50 m away with the phone until the link drops (~1 min).",
                                 "Walk back to the scooter.", "Wait 30 s WITHOUT unlocking the phone.",
                                 "Then unlock and look at the result."], place: .scooterHome),
        "c1": CheckGuide(proves: "iOS wakes the app when the scooter turns on.",
                         steps: ["Scooter off.", "Go to the Home Screen (don't swipe the app away) and lock the phone.",
                                 "Switch the scooter on.", "Wait 30 s."], place: .scooterHome),
        "c2": CheckGuide(proves: "Scooter data keeps arriving while the phone is locked.",
                         steps: ["After the c1 wake, keep the phone locked for about a minute."], place: .scooterHome),
        "c3": CheckGuide(proves: "GPS keeps recording while the phone is locked.",
                         steps: ["Location must be Always (h1).", "After the c1 wake (or Sensors → Start recording), lock the phone.",
                                 "Walk for ~2 minutes."], place: .scooterHome),
        "c4": CheckGuide(proves: "The barometer keeps recording while the phone is locked.",
                         steps: ["Same recording as c3."], place: .scooterHome),
        "c5": CheckGuide(proves: "After a phone restart, the scooter still wakes the app before you open it.",
                         steps: ["Scooter off.", "Restart the phone.", "Unlock once, but don't open CorckieApp.",
                                 "Switch the scooter on.", "Wait 30 s, then open the app."], place: .scooterHome),
        "c6": CheckGuide(proves: "The app can notify you when the scooter wakes it (the \"Going for a ride?\" chain).",
                         steps: ["Go to the Home Screen and lock the phone, then turn the scooter on.",
                                 "Before that, once: allow notifications (Permissions, step 1) and switch the scooter off.",
                                 "A \"Scooter on · …%\" / \"Going for a ride? Tap here\" notification arrives within ~30 s; tap it."], place: .scooterHome),
        "c6b": CheckGuide(proves: "The notification plays the Kick-off chime you chose.",
                          steps: ["Go to the Home Screen and lock the phone, then turn the scooter on.",
                                  "Before that, once: Permissions → step 6, Sounds ON (h2 ✅); ringer switch ON, volume up; scooter off.",
                                  "Did you hear the Kick-off chime with the notification?", "Tap Pass or Fail."], place: .scooterHome),
        "c6d": CheckGuide(proves: "The \"Going for a ride?\" notification does not stay around after the scooter is off.",
                          steps: ["Do the c6 steps until the notification is on the lock screen.",
                                  "Switch the scooter off (or leave it ~5 minutes until it switches itself off).",
                                  "Wait up to 2 minutes with the phone locked. Did the notification go? If it is still there, open the app: it must go then.",
                                  "Tap Pass if it went by itself or when you opened the app; Fail if it stayed (add a Note which)."], place: .scooterHome),
        "c7": CheckGuide(proves: "The wake-up and recording also work in Low Power Mode.",
                         steps: ["Turn Low Power Mode on (Control Centre or Settings → Battery).", "Scooter off; app in the background; lock the phone.",
                                 "Switch the scooter on and walk for ~1 minute.", "Unlock and look; then turn Low Power Mode off if you like."], place: .scooterHome),
        "c8": CheckGuide(proves: "A whole ride records with the phone locked: no data gaps, and how much phone battery it costs.",
                         steps: ["First, once: Permissions → Location → Always (h1 ✅).",
                                 "Before riding: Developer → Sensors → Start recording (the timer starts).",
                                 "Lock the phone and keep it locked; ride 20+ minutes.",
                                 "After the ride: unlock, Sensors → Stop recording (the result shows after 20 min).",
                                 "Export: the whole ride comes along (c8-scooter-packets, c8-location, c8-barometer)."], place: .ride),
        "d1": CheckGuide(proves: "The fake scooter replays your real ride 1 with the right numbers.",
                         steps: ["Run all automatic, or: Simulated scooter → Ride 1 · 50× · No fault → Start."], place: .noScooter),
        "d2": CheckGuide(proves: "The app can write to the backup folder you picked.",
                         steps: ["Developer → Backup folder → Pick folder (e.g. iCloud Drive › CorckieApp).", "Write test file."], place: .noScooter),
        "d3": CheckGuide(proves: "The backup folder still works after a phone restart.",
                         steps: ["Restart the phone.", "Developer → Backup folder → Write test file."], place: .noScooter),
        "d4": CheckGuide(proves: "The app notices when it crashed.",
                         steps: ["Developer → Crash catcher → Crash the app now.", "Open the app again."], place: .noScooter),
        "d5": CheckGuide(proves: "iOS's own crash reports reach the app.",
                         steps: ["Arrives by itself up to a day after d4."], place: .passive),
        "d6": CheckGuide(proves: "Errors are stored in the database for the export.",
                         steps: ["Run all automatic, or: Crash catcher → Write a test entry."], place: .noScooter),
        "u1": CheckGuide(proves: "Running checks show how far along they are, and multi-step checks tick their own steps (so you never have to guess).",
                         steps: ["Developer → Checks → tap Run all automatic: a bar and \"Step N of 8\" appear.",
                                 "While it runs, find d1 and d7 (All checks): a bar with the percentage shows on the one that is running.",
                                 "Look at b9, c5, c6 and c7: each has a Steps list (\"0 of 5\" …) with empty circles.",
                                 "With the scooter: start b8 (Scooter → Start 4-min test): a bar with \"3:20 left\" counts down.",
                                 "Tap Pass if the bars move and the steps tick as you do them, Fail if not (add a Note)."], place: .noScooter),
        "u2": CheckGuide(proves: "This build is 0.5 and carries the decided thresholds: speed warning on above 45 km/h and off below 43 (T99), safety margin +10% on decisions (T101).",
                         steps: ["Nothing to do: it marks itself when the app opens.", "Look at Settings → About for the version line (v1 · 0.5)."], place: .noScooter),
        "u3": CheckGuide(proves: "The fake scooter can also replay the phone's own GPS and barometer from a real ride, on the same clock as the scooter data. Later steps use this to test the ride engine without riding.",
                         steps: ["Developer → Checks → Run all automatic (it runs this check in a second).", "Or just open the app: nothing else to do.",
                                 "Result: how many GPS fixes and barometer readings replayed and how close the phone track is to the scooter log."], place: .noScooter),
        "u4": CheckGuide(proves: "Rides can be stored and removed: the ride, its samples, raw data, gaps and stops. Tests like this run in a temporary database, so your real rides are never touched.",
                         steps: ["Developer → Checks → Run all automatic (it runs this check in a second).",
                                 "Result: what was written, read back and deleted, and your real ride count before and after (it must be the same)."], place: .noScooter),
        "u8": CheckGuide(proves: "The Rides list rules work: the newest ride sits under Latest, the others are grouped by day, short hops (0.5 to 2 km) are kept apart, discarded pieces are hidden, the date filter (Today, This week, This month, All time) picks the right rides and a deleted ride disappears.",
                         steps: ["Developer → Checks → Run all automatic (it runs this check in a second).",
                                 "Result: one note per rule. Made-up rides in a temporary database are used, your real rides are never touched.",
                                 "Then open the Rides tab: empty now, with the filter menu top right (v1 label bottom right)."], place: .noScooter),
        "u9": CheckGuide(proves: "The ride engine starts a ride the right way: a ride begins when the wheel turns faster than 2 km/h and is confirmed by the motor current, the GPS speed or 50 m of GPS movement. Walking the scooter, spinning the wheel on the stand and a kick-start (the three autostart traps) are handled: walking is cancelled or trimmed away, a spin is cancelled within 20 s, a kick-start is kept. Start ride skips the confirm step and Not riding removes the ride without a trace.",
                         steps: ["Developer → Checks → Run all automatic (it runs this check in a second, on the fake scooter).",
                                 "Result: one tick per rule, with the seconds a spin took to cancel and the signal that confirmed the kick-start.",
                                 "The real-scooter versions (t1 walk, t2 spin, t3 kick) come with the Trap test in the M1 check list."], place: .noScooter),
        "u10": CheckGuide(proves: "The ride engine ends rides the right way and keeps the ride's stops: the scooter switching itself off ends the ride at once; a scooter that drops while you stand still ends it after 30 seconds; the auto-off after 5 minutes standing and 10 minutes of standstill end it too; the end time is always the last movement. Pushing the scooter (walking pace, no motor power, 30 s) is a walking stretch: its distance counts, but not in the average speed, and when the battery ran out the % is kept for the range. Switching off at a light and riding on within 10 minutes offers \"Same ride?\". If the app is killed mid-ride it carries on, or after more than 2 minutes the ride is closed as recovered.",
                          steps: ["Developer → Checks → Run all automatic (it runs this check in a few seconds, on the fake scooter).",
                                  "Result: one tick per rule, with the seconds and kilometres it found.",
                                  "The real versions (e2 scooter off, e3 Same ride, a real push of ~100 m) come with the M1 check list."], place: .noScooter),
        "u11": CheckGuide(proves: "When the scooter link drops mid-ride the phone takes over, but only after about 5 seconds, so a 1-second drop (seen 4 times on build 27) changes nothing. Then the speed comes from GPS (smoothed over 3 s, labelled \"GPS\"), the battery shows \"~N% est.\", and the stretch is kept as a gap; on reconnect the scooter numbers come back and the odometer fills in the distance. Ride totals stay scooter-only. The speed warning turns red with SLOW above 45 km/h and clears below 43, on the scooter's speed and on GPS speed while disconnected, without flickering.",
                          steps: ["Developer → Checks → Run all automatic (it runs this check in a second, on the fake scooter).",
                                  "Result: one tick per rule, with the seconds the warning switched on and off and the metres the odometer filled in.",
                                  "The real versions (p3 walk out of range and back, w4 speed warning on real rides) come with the M1 check list."], place: .noScooter),
        "u13": CheckGuide(proves: "Home shows the right thing in every state: first use and a scooter that is not connected show the amber Connect your scooter (never Start ride, because no ride can start before the connection is confirmed); a connected scooter shows its battery and Start ride; a connect that has not worked after 30 seconds says Can't find the scooter · Is it switched on? with Try again; a ride in progress says so.",
                          steps: ["Developer → Checks → Run all automatic (runs in a second).",
                                  "Result: one tick per state.",
                                  "Then open Home: with the scooter off it shows Scooter not connected and when you last saw it; switch the scooter on and Start ride appears."], place: .noScooter),
        "o1": CheckGuide(proves: "Onboarding takes three presses: Connect (the scooter that was found), Allow (location Always and motion, iOS asks) and Allow or Not now (notifications with sound). Then you are on Home. No tour.",
                         steps: ["Developer → Show onboarding (your scooter stays paired).",
                                 "Press Connect, then Allow (answer the iOS prompts), then Allow or Not now.",
                                 "The check turns green with the number of presses. Run all automatic marks the rules too."], place: .noScooter),
        "u12": CheckGuide(proves: "The Recorder works end to end: the fake scooter plays rides 1 and 2 into the same Recorder that records your real rides (ride engine, a sample every 5 seconds, the raw scooter packets, stops, the ride row), into a temporary database, and the stored ride gives the measured totals: about 437 Wh and 16.3 km, 322 Wh and 13.7 km. Then the app is \"killed\" mid-ride and opened again 10 minutes later: the ride is closed as recovered at its last sample. Your real rides are never touched.",
                          steps: ["Developer → Checks → Run all automatic (this step takes about 10 seconds).",
                                  "Result: energy, distance, end reason, samples and raw chunks per ride, the recovered ride, and your real ride count before and after (must be the same).",
                                  "The real version: ride with the phone locked (x1 in the M1 check list); the ride is recorded in the background."], place: .noScooter),
        "u5": CheckGuide(proves: "The ride numbers (time, distance, speeds, top speed, battery energy, temperature) can be worked out from the samples stored every 5 seconds, and they match the two rides measured by hand.",
                         steps: ["Developer → Checks → Run all automatic (it runs this check in a second).",
                                 "Result: ride 1 should read about 437 Wh and 16.3 km, ride 2 about 322 Wh and 13.7 km."], place: .noScooter),
        "u6": CheckGuide(proves: "The safety rules of the live ride screen and the message limits work: SLOW above 45 km/h and off below 43, GPS speed always labelled, banners can't be tapped while moving, at most 2 messages at ride start, hot once, very hot until it cools, one \"Going for a ride?\" per power-on.",
                         steps: ["Developer → Checks → Run all automatic (it runs this check in a second).",
                                 "Result: a list of ticks, one per rule. Any cross is a failure."], place: .noScooter),
        "u7": CheckGuide(proves: "The \"Going for a ride?\" rules: one notification per power-on (3 reconnect blips do not send more), sent at night too, never with the app open or during a ride, removed when the ride starts or the scooter is off. Every decision is written to the message log.",
                         steps: ["Developer → Checks → Run all automatic (it runs this check in a second).",
                                 "Result: a list of ticks, one per rule, and how many log rows were written."], place: .noScooter),
        "d7": CheckGuide(proves: "When the scooter drops mid-ride, the phone takes over (GPS speed) and totals stay scooter-only.",
                         steps: ["Run all automatic, or: Simulated scooter → Fault \"D7 · Disconnect at 40%\" → 50× → Start."], place: .noScooter),
        "d8": CheckGuide(proves: "Simulated rides never touch your real data.",
                         steps: ["Checked after every simulator run (Run all automatic does one)."], place: .noScooter),
        "d9": CheckGuide(proves: "A backup can be restored with every row intact.",
                         steps: ["Run all automatic, or: Backup folder → Test backup + restore."], place: .noScooter),
        "e1": CheckGuide(proves: "The fuel price setting is ready (manual in v1).",
                         steps: ["Nothing to do. Change it in Settings → Fuel price."], place: .noScooter),
        "e2": CheckGuide(proves: "Holidays download from Hebcal.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e3": CheckGuide(proves: "The weather forecast downloads.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e3b": CheckGuide(proves: "The forecast works for your real area, not a test point.",
                          steps: ["Location allowed (h1).", "Run all automatic (with internet)."], place: .noScooter),
        "e4": CheckGuide(proves: "The backup forecast (MET Norway) downloads.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e5": CheckGuide(proves: "Yesterday's weather downloads (for ride factors).", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e6": CheckGuide(proves: "Map elevation downloads.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e6b": CheckGuide(proves: "Elevation works for your real area.", steps: ["Location allowed (h1).", "Run all automatic (with internet)."], place: .noScooter),
        "e7": CheckGuide(proves: "Map tiles for Ride Replay download.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e8": CheckGuide(proves: "With no internet every source falls back calmly.",
                         steps: ["Turn airplane mode on.", "Developer → Outside data → Run all (~20 s).", "Turn airplane mode off."], place: .noScooter),
        "f1": CheckGuide(proves: "The barometer sees the arch bridge as a climb.", steps: ["Done (your verdict, 4 Oct)."], place: .ride),
        "f2": CheckGuide(proves: "The live numbers are readable on the handlebar mount.",
                         steps: ["Developer → Readability → Normal, phone on the mount.", "Tap Pass or Fail."], place: .ride),
        "f3": CheckGuide(proves: "The sunlight style is readable in direct sun.",
                         steps: ["Readability → Sunlight, in direct sun.", "Tap Pass or Fail."], place: .ride),
        "g1": CheckGuide(proves: "Everything reaches Claude in one file.",
                         steps: ["Developer → Results → Prepare export → Share → send to Claude."], place: .noScooter)
    ]
}
