import Foundation

/// The ⓘ text of every check (M1-00, B07): what it proves, numbered steps, and where it
/// happens (for the To do list). "Expected" comes from the check itself.
struct CheckGuide {
    enum Place: String, CaseIterable {
        case noScooter = "No scooter"
        case scooterHome = "Scooter at home"
        case ride = "On a ride"
        case passive = "Passive"
    }

    private static let routeStepSim = "Developer → Simulated scooter → Run on the real screens."

    let proves: String
    let steps: [String]
    let place: Place

    static func of(_ id: String) -> CheckGuide {
        all[id] ?? CheckGuide(proves: "—", steps: ["See the check's description."], place: .noScooter)
    }

    static let all: [String: CheckGuide] = [
        "h2": CheckGuide(proves: "Notification sounds are on, so the Kick-off chime can play (B10).",
                         steps: ["Developer → Permissions → step 1 (allow notifications with sounds).",
                                 "If Sounds still isn't on: step 6 → iPhone Settings → Notifications → CorckieApp → Sounds ON.",
                                 "Come back: the check updates by itself."], place: .noScooter),
        "h1": CheckGuide(proves: "The app has every permission v1 needs to record rides with the phone in your pocket.",
                         steps: ["Developer → Permissions.", "Do steps 1–6 top to bottom: notifications (with sounds), location While Using, then Always, motion, Bluetooth, sounds.",
                                 "If a prompt doesn't appear, the button opens iPhone Settings → CorckieApp.",
                                 "Come back to the app: the check updates by itself."], place: .noScooter),
        "a1": CheckGuide(proves: "The cloud-built app installs and starts on your iPhone.",
                         steps: ["Install the .ipa with SideStore.", "Open CorckieApp once."], place: .noScooter),
        "a2": CheckGuide(proves: "The Home Screen shows the right name and the scooter icon.",
                         steps: ["Go to the Home Screen.", "Look at the icon and the name under it.", "Tap Pass or Fail."], place: .noScooter),
        "a7": CheckGuide(proves: "\"v1\" is visible inside the app on every screen.",
                         steps: ["Visit each tab, Settings, Developer, Checks and two tool screens.",
                                 "Each time look at the bottom-right corner.", "Tap Pass or Fail."], place: .noScooter),
        "a3": CheckGuide(proves: "The app keeps its permanent ID, so updates keep your data.",
                         steps: ["Nothing to do: it marks itself at every launch."], place: .noScooter),
        "a4": CheckGuide(proves: "Installing a new build over the old one keeps all data.",
                         steps: ["In SideStore, install the new .ipa over the existing app (don't delete the app).",
                                 "Open CorckieApp: the check marks itself."], place: .noScooter),
        "a5": CheckGuide(proves: "SideStore renews the 7-day signing by itself.",
                         steps: ["Don't tap Refresh in SideStore for a few days.",
                                 "Before day 7, open SideStore: has the expiry date moved on by itself?", "Tap Pass or Fail."], place: .passive),
        "a6": CheckGuide(proves: "The database opened and is up to date (data versioning).",
                         steps: ["Nothing to do: it marks itself at every launch."], place: .noScooter),
        "b1": CheckGuide(proves: "The app finds and connects to the scooter.",
                         steps: ["Switch the scooter on.", "Developer → Scooter.", "Wait about 10 s."], place: .scooterHome),
        "b2": CheckGuide(proves: "The scooter's data is decoded into sensible numbers.",
                         steps: ["Stay on Developer → Scooter with the scooter on for ~10 s."], place: .scooterHome),
        "b3": CheckGuide(proves: "The scooter's firmware is the one the decoder was built for.",
                         steps: ["Read automatically when the scooter connects."], place: .scooterHome),
        "b4": CheckGuide(proves: "The app only reads from the scooter: it never sends anything.",
                         steps: ["Read automatically when the scooter connects."], place: .scooterHome),
        "b5": CheckGuide(proves: "Whether the scooter reports a lock state.",
                         steps: ["Developer → Scooter → Lock: Record.", "Lock and unlock 3 times, ~5 s apart.",
                                 "Stop and check (or tap \"No lock on this scooter\")."], place: .scooterHome),
        "b8": CheckGuide(proves: "The Bluetooth link holds for 4 minutes with nothing happening (B04). The scooter switches itself off after ~5 min standing, so the test is 4 min.",
                         steps: ["iPhone Settings → Display & Brightness → Auto-Lock → Never (set it back afterwards).",
                                 "Scooter on, standing still.", "Developer → Scooter → Start 4-min test.",
                                 "Keep the phone UNLOCKED on this screen for the full 4 minutes: don't switch apps or lock it.",
                                 "The result shows at 4:00."], place: .scooterHome),
        "b9": CheckGuide(proves: "When the scooter goes out of range, the app reconnects by itself when you come back.",
                         steps: ["Scooter on. Developer → Scooter → Arm range test.", "Lock the phone.",
                                 "Walk 30–50 m away with the phone until the link drops (~1 min).",
                                 "Walk back to the scooter.", "Wait 30 s WITHOUT unlocking the phone.",
                                 "Then unlock and look at the result."], place: .scooterHome),
        "c1": CheckGuide(proves: "iOS wakes the app when the scooter turns on.",
                         steps: ["Scooter off.", "Go to the Home Screen (don't swipe the app away) and lock the phone.",
                                 "Switch the scooter on.", "Wait 30 s."], place: .scooterHome),
        "c2": CheckGuide(proves: "Scooter data keeps arriving while the phone is locked.",
                         steps: ["After the c1 wake, keep the phone locked for about a minute."], place: .scooterHome),
        "c3": CheckGuide(proves: "GPS keeps recording while the phone is locked.",
                         steps: ["Location must be Always (h1).", "After the c1 wake (or Sensors → Start recording), lock the phone.",
                                 "Walk for ~2 minutes."], place: .scooterHome),
        "c4": CheckGuide(proves: "The barometer keeps recording while the phone is locked.",
                         steps: ["Same recording as c3."], place: .scooterHome),
        "c5": CheckGuide(proves: "After a phone restart, the scooter still wakes the app before you open it.",
                         steps: ["Scooter off.", "Restart the phone.", "Unlock once, but don't open CorckieApp.",
                                 "Switch the scooter on.", "Wait 30 s, then open the app."], place: .scooterHome),
        "c6": CheckGuide(proves: "The app can notify you when the scooter wakes it (the \"Going for a ride?\" chain).",
                         steps: ["Go to the Home Screen and lock the phone, then turn the scooter on.",
                                 "Before that, once: allow notifications (Permissions, step 1) and switch the scooter off.",
                                 "A \"Scooter on · …%\" / \"Going for a ride? Tap here\" notification arrives within ~30 s; tap it."], place: .scooterHome),
        "c6b": CheckGuide(proves: "The notification plays the Kick-off chime you chose.",
                          steps: ["Go to the Home Screen and lock the phone, then turn the scooter on.",
                                  "Before that, once: Permissions → step 6, Sounds ON (h2 ✅); ringer switch ON, volume up; scooter off.",
                                  "Did you hear the Kick-off chime with the notification?", "Tap Pass or Fail."], place: .scooterHome),
        "c6d": CheckGuide(proves: "The \"Going for a ride?\" notification does not stay around after the scooter is off.",
                          steps: ["Do the c6 steps until the notification is on the lock screen.",
                                  "Switch the scooter off (or leave it ~5 minutes until it switches itself off).",
                                  "Wait up to 2 minutes with the phone locked. Did the notification go? If it is still there, open the app: it must go then.",
                                  "Tap Pass if it went by itself or when you opened the app; Fail if it stayed (add a Note which)."], place: .scooterHome),
        "c7": CheckGuide(proves: "The wake-up and recording also work in Low Power Mode.",
                         steps: ["Turn Low Power Mode on (Control Centre or Settings → Battery).", "Scooter off; app in the background; lock the phone.",
                                 "Switch the scooter on and walk for ~1 minute.", "Unlock and look; then turn Low Power Mode off if you like."], place: .scooterHome),
        "c8": CheckGuide(proves: "A whole ride records with the phone locked: no data gaps, and how much phone battery it costs.",
                         steps: ["First, once: Permissions → Location → Always (h1 ✅).",
                                 "Before riding: Developer → Sensors → Start recording (the timer starts).",
                                 "Lock the phone and keep it locked; ride 20+ minutes.",
                                 "After the ride: unlock, Sensors → Stop recording (the result shows after 20 min).",
                                 "Export: the whole ride comes along (c8-scooter-packets, c8-location, c8-barometer)."], place: .ride),
        "d1": CheckGuide(proves: "The fake scooter replays your real ride 1 with the right numbers.",
                         steps: ["Run all automatic, or: Simulated scooter → Ride 1 · 50× · No fault → Start."], place: .noScooter),
        "d2": CheckGuide(proves: "The app can write to the backup folder you picked.",
                         steps: ["Developer → Backup folder → Pick folder (e.g. iCloud Drive › CorckieApp).", "Write test file."], place: .noScooter),
        "d3": CheckGuide(proves: "The backup folder still works after a phone restart.",
                         steps: ["Restart the phone.", "Developer → Backup folder → Write test file."], place: .noScooter),
        "d4": CheckGuide(proves: "The app notices when it crashed.",
                         steps: ["Developer → Crash catcher → Crash the app now.", "Open the app again."], place: .noScooter),
        "d5": CheckGuide(proves: "iOS's own crash reports reach the app.",
                         steps: ["Arrives by itself up to a day after d4."], place: .passive),
        "d6": CheckGuide(proves: "Errors are stored in the database for the export.",
                         steps: ["Run all automatic, or: Crash catcher → Write a test entry."], place: .noScooter),
        "u1": CheckGuide(proves: "Running checks show how far along they are, and multi-step checks tick their own steps (so you never have to guess).",
                         steps: ["Developer → Checks → tap Run all automatic: a bar and \"Step N of 8\" appear.",
                                 "While it runs, find d1 and d7 (All checks): a bar with the percentage shows on the one that is running.",
                                 "Look at b9, c5, c6 and c7: each has a Steps list (\"0 of 5\" …) with empty circles.",
                                 "With the scooter: start b8 (Scooter → Start 4-min test): a bar with \"3:20 left\" counts down.",
                                 "Tap Pass if the bars move and the steps tick as you do them, Fail if not (add a Note)."], place: .noScooter),
        "u2": CheckGuide(proves: "This build is 0.6 and carries the decided thresholds: speed warning on above 45 km/h and off below 43 (T99), safety margin +10% on decisions (T101).",
                         steps: ["Nothing to do: it marks itself when the app opens.", "Look at Settings → About for the version line (v1 · 0.6)."], place: .noScooter),
        "u3": CheckGuide(proves: "The fake scooter can also replay the phone's own GPS and barometer from a real ride, on the same clock as the scooter data. Later steps use this to test the ride engine without riding.",
                         steps: ["Developer → Checks → Run all automatic (it runs this check in a second).", "Or just open the app: nothing else to do.",
                                 "Result: how many GPS fixes and barometer readings replayed and how close the phone track is to the scooter log."], place: .noScooter),
        "u4": CheckGuide(proves: "Rides can be stored and removed: the ride, its samples, raw data, gaps and stops. Tests like this run in a temporary database, so your real rides are never touched.",
                         steps: ["Developer → Checks → Run all automatic (it runs this check in a second).",
                                 "Result: what was written, read back and deleted, and your real ride count before and after (it must be the same)."], place: .noScooter),
        "u8": CheckGuide(proves: "The Rides list rules work: the newest ride sits under Latest, the others are grouped by day, short hops (0.5 to 2 km) are kept apart, discarded pieces are hidden, the date filter (Today, This week, This month, All time) picks the right rides and a deleted ride disappears.",
                         steps: ["Developer → Checks → Run all automatic (it runs this check in a second).",
                                 "Result: one note per rule. Made-up rides in a temporary database are used, your real rides are never touched.",
                                 "Then open the Rides tab: empty now, with the filter menu top right (v1 label bottom right)."], place: .noScooter),
        "u9": CheckGuide(proves: "The ride engine starts a ride the right way: a ride begins when the wheel turns faster than 2 km/h and is confirmed by the motor current, the GPS speed or 50 m of GPS movement. Walking the scooter, spinning the wheel on the stand and a kick-start (the three autostart traps) are handled: walking is cancelled or trimmed away, a spin is cancelled within 20 s, a kick-start is kept. Start ride skips the confirm step and Not riding removes the ride without a trace.",
                         steps: ["Developer → Checks → Run all automatic (it runs this check in a second, on the fake scooter).",
                                 "Result: one tick per rule, with the seconds a spin took to cancel and the signal that confirmed the kick-start.",
                                 "The real-scooter versions (t1 walk, t2 spin, t3 kick) come with the Trap test in the M1 check list."], place: .noScooter),
        "u10": CheckGuide(proves: "The ride engine ends rides the right way and keeps the ride's stops: the scooter switching itself off ends the ride at once; a scooter that drops while you stand still ends it after 30 seconds; the auto-off after 5 minutes standing and 10 minutes of standstill end it too; the end time is always the last movement. Pushing the scooter (walking pace, no motor power, 30 s) is a walking stretch: its distance counts, but not in the average speed, and when the battery ran out the % is kept for the range. Switching off at a light and riding on within 10 minutes offers \"Same ride?\". If the app is killed mid-ride it carries on, or after more than 2 minutes the ride is closed as recovered.",
                          steps: ["Developer → Checks → Run all automatic (it runs this check in a few seconds, on the fake scooter).",
                                  "Result: one tick per rule, with the seconds and kilometres it found.",
                                  "The real versions (e2 scooter off, e3 Same ride, a real push of ~100 m) come with the M1 check list."], place: .noScooter),
        "u11": CheckGuide(proves: "When the scooter link drops mid-ride the phone takes over, but only after about 5 seconds, so a 1-second drop (seen 4 times on build 27) changes nothing. Then the speed comes from GPS (smoothed over 3 s, labelled \"GPS\"), the battery shows \"~N% est.\", and the stretch is kept as a gap; on reconnect the scooter numbers come back and the odometer fills in the distance. Ride totals stay scooter-only. The speed warning turns red with SLOW above 45 km/h and clears below 43, on the scooter's speed and on GPS speed while disconnected, without flickering.",
                          steps: ["Developer → Checks → Run all automatic (it runs this check in a second, on the fake scooter).",
                                  "Result: one tick per rule, with the seconds the warning switched on and off and the metres the odometer filled in.",
                                  "The real versions (p3 walk out of range and back, w4 speed warning on real rides) come with the M1 check list."], place: .noScooter),
        "u16": CheckGuide(proves: "The backup files are real and readable: a full backup (a compressed copy of the whole database) and a small file per ride are written, read back and compared, latest.json holds the settings, and old full backups are removed so only the newest three stay. Nothing touches your real backup folder or rides.",
                          steps: ["Developer → Checks → Run all automatic (a second or two, in a temporary folder).",
                                  "Result: one tick per part.",
                                  "The real folder: Developer → Backup folder (d2), then finish a ride (d10)."], place: .noScooter),
        "q1": CheckGuide(proves: "Recording a ride does not drain the phone: at most 10% of its battery per 30 minutes of riding.",
                         steps: ["Ride 15 minutes or more with the phone not charging (the Recorder notes the phone battery at the start and at the end).",
                                 "Result: the % used per ride and per 30 minutes. Not judged when the phone was charging or the ride was shorter."], place: .ride),
        "d10": CheckGuide(proves: "After a real ride the app writes its backup to your folder: a ride file in CorckieApp Backup/rides, plus a full backup when the last one is a week old.",
                          steps: ["Developer → Backup folder → Pick folder (check d2 first).",
                                  "Finish a ride.",
                                  "Result: ✅ with the file name; Settings → Last backup shows the time. Open the folder in Files to see it."], place: .ride),
        "u15": CheckGuide(proves: "The ride summary (shown when a ride ends, and when you tap a ride in Rides) is built right from what was stored: time, moving time, distance, average speed, battery start to end, top speed, energy, stops, elevation and temperature, with a map path coloured by speed (dashed where the phone recorded alone, grey where you walked) and plain notes for a recovered ride, missing scooter or GPS readings and a hot scooter. No records, badges or comparisons. A ride without GPS shows a No GPS card instead of the map.",
                          steps: ["Developer → Checks → Run all automatic (runs in a second, on a made-up ride in a temporary database).",
                                  "Result: one tick per part.",
                                  "To look at the real screen: Rides → tap a ride (a ride you did, or a simulated one once M1-15 is in)."], place: .noScooter),
        "u14": CheckGuide(proves: "The live ride screen shows the right things and stays safe: the Ready view (opened from the Going for a ride? notification) shows the map, battery and speed 0 with no clock and no stop button, and is the only live view that can be closed; once a ride is on there is no close button, no tab bar and no swipe-down, and only holding the stop button for a full second ends the ride (a tap does nothing). The speed turns red with SLOW above 45 km/h and clears below 43; GPS speed is greyed and labelled GPS with the battery shown as ~N% est.; banners come one at a time and cannot be tapped from 5 km/h; No GPS shows after 10 seconds.",
                          steps: ["Developer → Checks → Run all automatic (runs in a second, on made-up readings).",
                                  "Result: one tick per rule.",
                                  "The real screens: Developer → Simulated scooter (arrives with M1-15), and a real ride (l3, f2, f3 in the M1 check list)."], place: .noScooter),
        "u13": CheckGuide(proves: "Home shows the right thing in every state: first use and a scooter that is not connected show the amber Connect your scooter (never Start ride, because no ride can start before the connection is confirmed); a connected scooter shows its battery and Start ride; a connect that has not worked after 30 seconds says Can't find the scooter · Is it switched on? with Try again; a ride in progress says so.",
                          steps: ["Developer → Checks → Run all automatic (runs in a second).",
                                  "Result: one tick per state.",
                                  "Then open Home: with the scooter off it shows Scooter not connected and when you last saw it; switch the scooter on and Start ride appears."], place: .noScooter),
        "o1": CheckGuide(proves: "Onboarding takes three presses: Connect (the scooter that was found), Allow (location Always and motion, iOS asks) and Allow or Not now (notifications with sound). Then you are on Home. No tour.",
                         steps: ["Developer → Show onboarding (your scooter stays paired).",
                                 "Press Connect, then Allow (answer the iOS prompts), then Allow or Not now.",
                                 "The check turns green with the number of presses. Run all automatic marks the rules too."], place: .noScooter),
        "u12": CheckGuide(proves: "The Recorder works end to end: the fake scooter plays rides 1 and 2 into the same Recorder that records your real rides (ride engine, a sample every 5 seconds, the raw scooter packets, stops, the ride row), into a temporary database, and the stored ride gives the measured totals: about 437 Wh and 16.3 km, 322 Wh and 13.7 km. Then the app is \"killed\" mid-ride and opened again 10 minutes later: the ride is closed as recovered at its last sample. Your real rides are never touched.",
                          steps: ["Developer → Checks → Run all automatic (this step takes about 10 seconds).",
                                  "Result: energy, distance, end reason, samples and raw chunks per ride, the recovered ride, and your real ride count before and after (must be the same).",
                                  "The real version: ride with the phone locked (x1 in the M1 check list); the ride is recorded in the background."], place: .noScooter),
        "u5": CheckGuide(proves: "The ride numbers (time, distance, speeds, top speed, battery energy, temperature) can be worked out from the samples stored every 5 seconds, and they match the two rides measured by hand.",
                         steps: ["Developer → Checks → Run all automatic (it runs this check in a second).",
                                 "Result: ride 1 should read about 437 Wh and 16.3 km, ride 2 about 322 Wh and 13.7 km."], place: .noScooter),
        "u6": CheckGuide(proves: "The safety rules of the live ride screen and the message limits work: SLOW above 45 km/h and off below 43, GPS speed always labelled, banners can't be tapped while moving, at most 2 messages at ride start, hot once, very hot until it cools, one \"Going for a ride?\" per power-on.",
                         steps: ["Developer → Checks → Run all automatic (it runs this check in a second).",
                                 "Result: a list of ticks, one per rule. Any cross is a failure."], place: .noScooter),
        "u7": CheckGuide(proves: "The \"Going for a ride?\" rules: one notification per power-on (3 reconnect blips do not send more), sent at night too, never with the app open or during a ride, removed when the ride starts or the scooter is off. Every decision is written to the message log.",
                         steps: ["Developer → Checks → Run all automatic (it runs this check in a second).",
                                 "Result: a list of ticks, one per rule, and how many log rows were written."], place: .noScooter),
        "d7": CheckGuide(proves: "When the scooter drops mid-ride, the phone takes over (GPS speed) and totals stay scooter-only.",
                         steps: ["Run all automatic, or: Simulated scooter → Fault \"D7 · Disconnect at 40%\" → 50× → Start."], place: .noScooter),
        "d8": CheckGuide(proves: "Simulated rides never touch your real data.",
                         steps: ["Checked after every simulator run (Run all automatic does one)."], place: .noScooter),
        "d11": CheckGuide(proves: "The fake scooter can run the real screens: Home, the live ride view and the ride summary, with a SIMULATED banner everywhere, and nothing simulated reaches your real rides or backups.",
                          steps: ["Developer → Simulated scooter → Run on the real screens.",
                                  "Pick \"Ride 2 with GPS\" and 50×, tap Start (the real scooter must be off).",
                                  "Watch: Home shows Ready, the live view opens by itself, then the ride summary. Every screen has the purple SIMULATED banner.",
                                  "Tap Done, open the Rides tab: the simulated ride is listed (banner still on).",
                                  "Back in Simulated scooter, tap End simulation: the Rides tab shows only your real rides again.",
                                  "Mark this check ✅ if all of that happened; d8 turns ✅ by itself."], place: .noScooter),
        "d9": CheckGuide(proves: "A backup can be restored with every row intact.",
                         steps: ["Run all automatic, or: Backup folder → Test backup + restore."], place: .noScooter),
        "e1": CheckGuide(proves: "The fuel price setting is ready (manual in v1).",
                         steps: ["Nothing to do. Change it in Settings → Fuel price."], place: .noScooter),
        "e2": CheckGuide(proves: "Holidays download from Hebcal.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e3": CheckGuide(proves: "The weather forecast downloads.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e3b": CheckGuide(proves: "The forecast works for your real area, not a test point.",
                          steps: ["Location allowed (h1).", "Run all automatic (with internet)."], place: .noScooter),
        "e4": CheckGuide(proves: "The backup forecast (MET Norway) downloads.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e5": CheckGuide(proves: "Yesterday's weather downloads (for ride factors).", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e6": CheckGuide(proves: "Map elevation downloads.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e6b": CheckGuide(proves: "Elevation works for your real area.", steps: ["Location allowed (h1).", "Run all automatic (with internet)."], place: .noScooter),
        "e7": CheckGuide(proves: "Map tiles for Ride Replay download.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e8": CheckGuide(proves: "With no internet every source falls back calmly.",
                         steps: ["Turn airplane mode on.", "Developer → Outside data → Run all (~20 s).", "Turn airplane mode off."], place: .noScooter),
        "f1": CheckGuide(proves: "The barometer sees the arch bridge as a climb.", steps: ["Done (your verdict, 4 Oct)."], place: .ride),
        "f2": CheckGuide(proves: "The live numbers are readable on the handlebar mount.",
                         steps: ["Developer → Readability → Normal, phone on the mount.", "Tap Pass or Fail."], place: .ride),
        "f3": CheckGuide(proves: "The sunlight style is readable in direct sun.",
                         steps: ["Readability → Sunlight, in direct sun.", "Tap Pass or Fail."], place: .ride),
        "u17": CheckGuide(proves: "The app finds your places and routes by itself: two rides between the same two spots (a start and an end that are close to each other, within 5% of the trip length, at least 100 m and at most 1 km) make a suggested route, and the second ride asks Save as route?. Parking a little differently (120 m away) still matches. A loop (start and end are the same spot), a ride with no GPS at one end, or a trip you said Not a route to never make a suggestion.",
                          steps: ["Developer → Checks → Run all automatic (runs in a second, on made-up rides on an imaginary map in a temporary database).",
                                   "Result: one tick per rule and how many milliseconds matching the last ride took.",
                                   "The screen versions (rt1 to rt3) use the simulator; the real one is rt13."], place: .noScooter),
        "u18": CheckGuide(proves: "A different way to the same place becomes a variant of the route (a stretch of at least 5% of the route, and at least 100 m, more than 50 m from the usual way). Different parking spots or GPS wobble do not. A variant is named after the longest street along its different part (the phone looks the street up; with no answer it is Variant 2), and a name you typed is never replaced. The way back is a separate route.",
                          steps: ["Developer → Checks → Run all automatic (runs in a second, on made-up rides in a temporary database).",
                                   "Result: one tick per rule.",
                                   "The screen versions (rt4 to rt6) use the simulator; the real one is rt17."], place: .noScooter),
        "u19": CheckGuide(proves: "A route's usual range is the middle 80% of its last 20 rides in the last 90 days (under 5 rides it is simply the shortest to the longest, and says based on N rides); times need 3 rides and battery needs 5. A ride is noticeably different only when it is outside the range by at least 1 minute or 2% and the route has 5 rides. Today is the route's median for the day and the usual leaving time (rush hour has its own number when it makes a big difference), shown honest; the battery a decision needs is that number plus 10% and is never shown as the estimate.",
                          steps: ["Developer → Checks → Run all automatic (runs in a second, on made-up rides).",
                                  "Result: one tick per rule, including Today without and with the 10% margin and the wider range when the factors and the past rides disagree."], place: .noScooter),
        "u20": CheckGuide(proves: "The route card and the Routes list are built right from rides stored on the phone: the title (the two place names, your own name, or Route 1), six stat ranges, the Today strip, the variants with the map, the elevation both ways (the other way is marked as an estimate until you ride it), and the newest rides. Sections with nothing to show are left out.",
                          steps: ["Developer → Checks → Run all automatic (a second or two, on 8 made-up rides in a temporary database).",
                                  "Result: one tick per part.", "Then look at the real screens with the simulator: rt7 and rt8."], place: .noScooter),
        "rt7": CheckGuide(proves: "The route card shows the right sections for a route with 6 rides.",
                          steps: [routeStepSim, "Run ROUTE-COMMUTE-6 at 50× and tap Save route on the second summary.", "After the run open the Routes tab and the route.",
                                  "Expected: the title and based on 6 rides, six ranges (battery needs 5 rides), the Today strip, the map with the path, the rides list. Tap Pass or Fail."], place: .noScooter),
        "rt8": CheckGuide(proves: "The Routes tab says what is going on: empty, a suggestion waiting, saved routes with their ranges.",
                          steps: ["Open the Routes tab with no rides: No routes yet · Ride the same trip twice and you will be asked to save it.", routeStepSim,
                                  "Run ROUTE-COMMUTE at 50× and do not save: the trip sits under Suggested routes.", "Open it, tap Save route: it moves up under Routes. Tap Pass or Fail."], place: .noScooter),
        "rt9": CheckGuide(proves: "You can rename a route (and clear the name again) and remove one; removing keeps the rides.",
                          steps: [routeStepSim, "Run ROUTE-COMMUTE, save the route, open it.", "Tap the three dots, Rename route, type Commute, Save: the title changes. Rename again with an empty name: the place names come back.",
                                  "Three dots, Remove route, confirm: the route is gone from the list; the Rides tab still has the rides. Tap Pass or Fail."], place: .noScooter),
        "d12": CheckGuide(proves: "Simulated rides never create places, routes or variants in your real data.",
                          steps: ["Run any simulator scenario on the real screens (Developer → Simulated scooter).", "Tap End simulation: the check marks itself with the real counts before and after."], place: .noScooter),
        "q2": CheckGuide(proves: "Working out where a finished ride belongs takes milliseconds, so closing a ride stays fast even after a year of rides.",
                         steps: ["Nothing to do: every ride that closes records how long it took.", "Result: the note says the milliseconds and how many earlier rides were compared."], place: .noScooter),
        "rt1": CheckGuide(proves: "After the same commute twice, the ride summary offers Save as route?, and a third trip joins the saved route.",
                          steps: [routeStepSim, "Pick the scenario ROUTE-COMMUTE (the same commute 3 times), 50×, tap Start; the real scooter must be off.",
                                  "Wait for the first summary (no card yet) and tap Done.", "The second summary shows a Save as route? card: tap Save route.",
                                  "After the third trip the summary says Route · (name) and that it is one of 3 rides.", "Tap End simulation when done. Tap Pass if all of that happened."], place: .noScooter),
        "rt2": CheckGuide(proves: "When you say Not a route, the app never offers that trip again.",
                          steps: [routeStepSim, "Run ROUTE-COMMUTE; on the second summary tap Not a route (the card goes away).",
                                  "Wait for the third trip: its summary must not show Save as route? either (the app remembers). Tap Pass or Fail."], place: .noScooter),
        "rt3": CheckGuide(proves: "A round trip (a loop) and a ride with no GPS at its start are never offered as routes.",
                          steps: [routeStepSim, "Run ROUTE-LOOP at 50×: two round trips, no Save as route? card.", "End simulation, then run ROUTE-NOGPS at 50×: the second trip lost GPS at its start, no card.", "Tap Pass or Fail."], place: .noScooter),
        "rt4": CheckGuide(proves: "Riding to the same place another way creates a second variant, shown on the route card.",
                          steps: [routeStepSim, "Run ROUTE-VARIANT at 50× (twice the usual way, then a detour); on the second summary tap Save route.",
                                  "After the run, open the Routes tab, the route, and look at Variants.",
                                  "Expected: two variants; the second is called Variant 2 on the imaginary map. Tap Pass or Fail."], place: .noScooter),
        "rt5": CheckGuide(proves: "With no internet the variant keeps its fallback name and nothing breaks or waits.",
                          steps: ["Turn airplane mode on.", routeStepSim, "Run ROUTE-VARIANT at 50×.", "Variant 2 stays; the app does not freeze. Turn airplane mode off. Tap Pass or Fail."], place: .noScooter),
        "rt6": CheckGuide(proves: "A to B and B to A are two different routes.",
                          steps: [routeStepSim, "Run ROUTE-THEREBACK at 50× (A to B, B to A, twice each).", "Save the suggestion on the second summary of each direction.",
                                  "Routes tab: two routes listed, A to B and B to A. Tap Pass or Fail."], place: .noScooter),
        "u21": CheckGuide(proves: "The Routes list greys out a route the battery cannot reach, using a 10% safety margin on top of what the route needs and a 5% reserve. Exactly enough still fits, a tenth of a percent less is greyed. When there fits but not the way back, the row gets the amber chip One way only; a round trip with less than 10% spare gets Tight. If you can charge at the end, only the way there has to fit. With fewer than 5 rides with a battery value nothing is said. When the scooter is off, the last seen percentage is used and its age is shown. The number shown is always the honest estimate; only the decision carries the margin.",
                          steps: ["Developer → Checks → Run all automatic (a second or two, on 12 made-up rides in a temporary database).",
                                  "Result: one tick per rule. The screen version is rt10."], place: .noScooter),
        "rt10": CheckGuide(proves: "A route you cannot reach with the battery you have is greyed with the reason, and a route you can reach but not return from has an amber chip. Both can still be opened.",
                           steps: [routeStepSim, "Run ROUTE-LOWBATT at 50× (6 trips each way, the battery ends at 10%). On the second summary of each direction tap Save route.",
                                   "Wait for the end (about 6 minutes), then open the Routes tab without ending the simulation.",
                                   "Expected: Route 2 (the way back) greyed with Not enough battery and a line saying what it uses, Route 1 with the amber chip One way only. Open each one: it works. Tap Pass or Fail."], place: .noScooter),
        "rt13": CheckGuide(proves: "The app learns a real route by itself after the same real trip twice.",
                           steps: ["Ride the same trip twice (two real rides between the same two places, any day).", "After the second ride the summary shows Save as route?.", "Tap Save route. Tap Pass or Fail (the Note says where it started or ended if the places look wrong)."], place: .ride),
        "rt16": CheckGuide(proves: "Parking 50 to 150 m from the first start does not make a new route.",
                           steps: ["Ride the trip once (first start).", "Next time park a little away (50 to 150 m) and ride the same trip.", "The ride joins the same route (no new suggestion). Tap Pass or Fail."], place: .ride),
        "rt17": CheckGuide(proves: "A real detour is a new variant and is named after its street.",
                           steps: ["Internet on.", "Ride to the same place by another street (at least about 5% of the trip and 100 m different).", "Open the route card: a second variant via the street. If no street came back it is Variant 2. Tap Pass or Fail."], place: .ride),
        "u22": CheckGuide(proves: "The Where to? chip shows only once a route is saved, and the arrival time is worked out from where you are on the route and how fast you are going: on pace it is the rest of today's estimate, running late it grows (blended by how many km you have done), off the route it falls back to the straight distance at your usual speed. The line changes at most every 30 seconds, or at once when it moves by a minute.",
                          steps: ["Developer → Checks → Run all automatic (a second or two, on 6 made-up commutes in a temporary database).", "Result: one tick per rule. The screen version is rt11."], place: .noScooter),
        "u23": CheckGuide(proves: "Arrive by works out when to leave: the time to arrive minus today's estimate minus a margin (the gap between your typical and your slow rides). It re-checks the estimate at the leave time, so a trip that crosses into rush hour is settled in at most 3 steps. The reminder is sent at the leave time, held to 07:00 if that falls in the quiet hours (22:00 to 07:00) or dropped if 07:00 would be too late, and replaced only when the new time is 2 minutes or more earlier.",
                          steps: ["Developer → Checks → Run all automatic.", "Result: one tick per rule. The screen version is rt14."], place: .noScooter),
        "rt14": CheckGuide(proves: "Arrive by shows when to leave and sets a reminder.",
                           steps: [routeStepSim, "Run ROUTE-COMMUTE-6 at 50×, tap Save route on the second summary, and let it finish.", "Routes → the route → Arrive by: pick a time about 40 minutes from now.",
                                   "Expected: Leave by HH:MM with today's minutes and a margin. Switch Remind me when to leave on: a line says Reminder set for HH:MM. Lock the phone: the notification comes at that time (allow notifications first). Tap Pass or Fail."], place: .noScooter),
        "u24": CheckGuide(proves: "When GPS is lost on a route the app knows, the dot keeps moving along the route by the wheel distance (hollow, with No GPS) and is within 30 m of the real path after 2 km. Off the route, or with no route, it stays frozen and grey as before.",
                          steps: ["Developer → Checks → Run all automatic.", "Result: one tick per rule. The screen version is rt12."], place: .noScooter),
        "rt11": CheckGuide(proves: "Where to? on Home appears once you have a saved route, and the live screen shows the arrival time and counts down.",
                           steps: [routeStepSim, "Run ROUTE-COMMUTE-6 at 5× and tap Save route on the second summary.", "When the third trip is over, open Home: a Where to? chip with the route. Tap it: Today for that route shows.",
                                   "Watch the fourth trip's live screen: a line like Route 1 · arrive ~8:56 · 9 min left under the top of the map, counting down without jumping. Tap Pass or Fail."], place: .noScooter),
        "rt12": CheckGuide(proves: "With no GPS on a known route the dot keeps moving along the route.",
                           steps: [routeStepSim, "Run ROUTE-GPSLOSS at 5× and tap Save route on the second summary. Tap the route's chip under Where to? on Home before the fourth trip starts.",
                                   "During the fourth trip GPS is lost for about 5 minutes: the dot turns hollow, No GPS shows, the dot keeps moving along the route; solid again when GPS returns. Tap Pass or Fail."], place: .noScooter),
        "rt19": CheckGuide(proves: "On a real ride the arrival time is believable.",
                           steps: ["Home → Where to? → tap the route you are about to ride → Start.", "Watch the arrival time; at the end it should have been right within about 2 minutes and not jumped. Tap Pass or Fail."], place: .ride),
        "rt20": CheckGuide(proves: "On a real ride through a place without GPS the dot keeps moving.",
                           steps: ["Pick the route under Where to?, ride it through a tunnel or underpass.", "The dot keeps moving hollow with No GPS and is right again afterwards. Tap Pass or Fail."], place: .ride),
        "g1": CheckGuide(proves: "Everything reaches Claude in one file.",
                         steps: ["Developer → Results → Prepare export → Share → send to Claude."], place: .noScooter)
    ]
}
