import Foundation

/// The ⓘ text of every check (M1-00, B07): what it proves, numbered steps, and where it
/// happens (for the To do list). "Expected" comes from the check itself.
struct CheckGuide {
    enum Place: String, CaseIterable {
        case noScooter = "No scooter"
        case scooterHome = "Scooter at home"
        case ride = "On a ride"
        case passive = "Passive"
    }

    let proves: String
    let steps: [String]
    let place: Place

    static func of(_ id: String) -> CheckGuide {
        all[id] ?? CheckGuide(proves: "—", steps: ["See the check's description."], place: .noScooter)
    }

    static let all: [String: CheckGuide] = [
        "h1": CheckGuide(proves: "The app has every permission v1 needs to record rides with the phone in your pocket.",
                         steps: ["Developer → Permissions.", "Tap \"Ask for notifications\" and allow.",
                                 "Tap \"Open iPhone Settings for CorckieApp\" → Location → Always.",
                                 "Come back to the app: the check updates by itself."], place: .noScooter),
        "a1": CheckGuide(proves: "The cloud-built app installs and starts on your iPhone.",
                         steps: ["Install the .ipa with SideStore.", "Open CorckieApp once."], place: .noScooter),
        "a2": CheckGuide(proves: "The Home Screen shows the right name and the scooter icon.",
                         steps: ["Go to the Home Screen.", "Look at the icon and the name under it.", "Tap Pass or Fail."], place: .noScooter),
        "a7": CheckGuide(proves: "\"v1\" is visible inside the app on every screen.",
                         steps: ["Visit each tab, Settings, Developer, Checks and two tool screens.",
                                 "Each time look at the bottom-right corner.", "Tap Pass or Fail."], place: .noScooter),
        "a3": CheckGuide(proves: "The app keeps its permanent ID, so updates keep your data.",
                         steps: ["Nothing to do: it marks itself at every launch."], place: .noScooter),
        "a4": CheckGuide(proves: "Installing a new build over the old one keeps all data.",
                         steps: ["In SideStore, install the new .ipa over the existing app (don't delete the app).",
                                 "Open CorckieApp: the check marks itself."], place: .noScooter),
        "a5": CheckGuide(proves: "SideStore renews the 7-day signing by itself.",
                         steps: ["Don't tap Refresh in SideStore for a few days.",
                                 "Before day 7, open SideStore: has the expiry date moved on by itself?", "Tap Pass or Fail."], place: .passive),
        "a6": CheckGuide(proves: "The database opened and is up to date (data versioning).",
                         steps: ["Nothing to do: it marks itself at every launch."], place: .noScooter),
        "b1": CheckGuide(proves: "The app finds and connects to the scooter.",
                         steps: ["Switch the scooter on.", "Developer → Scooter.", "Wait about 10 s."], place: .scooterHome),
        "b2": CheckGuide(proves: "The scooter's data is decoded into sensible numbers.",
                         steps: ["Stay on Developer → Scooter with the scooter on for ~10 s."], place: .scooterHome),
        "b3": CheckGuide(proves: "The scooter's firmware is the one the decoder was built for.",
                         steps: ["Read automatically when the scooter connects."], place: .scooterHome),
        "b4": CheckGuide(proves: "The app only reads from the scooter: it never sends anything.",
                         steps: ["Read automatically when the scooter connects."], place: .scooterHome),
        "b5": CheckGuide(proves: "Whether the scooter reports a lock state.",
                         steps: ["Developer → Scooter → Lock: Record.", "Lock and unlock 3 times, ~5 s apart.",
                                 "Stop and check (or tap \"No lock on this scooter\")."], place: .scooterHome),
        "b8": CheckGuide(proves: "The Bluetooth link holds for 10 minutes with nothing happening (B04).",
                         steps: ["iPhone Settings → Display & Brightness → Auto-Lock → Never (set it back afterwards).",
                                 "Scooter on, standing still.", "Developer → Scooter → Start 10-min test.",
                                 "Keep the phone UNLOCKED on this screen for the full 10 minutes: don't switch apps or lock it.",
                                 "The result shows at 10:00."], place: .scooterHome),
        "b9": CheckGuide(proves: "When the scooter goes out of range, the app reconnects by itself when you come back.",
                         steps: ["Scooter on. Developer → Scooter → Arm range test.", "Lock the phone.",
                                 "Walk 30–50 m away with the phone until the link drops (~1 min).",
                                 "Walk back to the scooter.", "Wait 30 s WITHOUT unlocking the phone.",
                                 "Then unlock and look at the result."], place: .scooterHome),
        "c1": CheckGuide(proves: "iOS wakes the app when the scooter turns on.",
                         steps: ["Scooter off.", "Go to the Home Screen (don't swipe the app away) and lock the phone.",
                                 "Switch the scooter on.", "Wait 30 s."], place: .scooterHome),
        "c2": CheckGuide(proves: "Scooter data keeps arriving while the phone is locked.",
                         steps: ["After the c1 wake, keep the phone locked for about a minute."], place: .scooterHome),
        "c3": CheckGuide(proves: "GPS keeps recording while the phone is locked.",
                         steps: ["Location must be Always (h1).", "After the c1 wake (or Sensors → Start recording), lock the phone.",
                                 "Walk for ~2 minutes."], place: .scooterHome),
        "c4": CheckGuide(proves: "The barometer keeps recording while the phone is locked.",
                         steps: ["Same recording as c3."], place: .scooterHome),
        "c5": CheckGuide(proves: "After a phone restart, the scooter still wakes the app before you open it.",
                         steps: ["Scooter off.", "Restart the phone.", "Unlock once, but don't open CorckieApp.",
                                 "Switch the scooter on.", "Wait 30 s, then open the app."], place: .scooterHome),
        "c6": CheckGuide(proves: "The app can notify you when the scooter wakes it (the \"Going for a ride?\" chain).",
                         steps: ["Allow notifications (h1).", "App in the background, phone locked, scooter off.",
                                 "Switch the scooter on.", "A \"Scooter on · …% · test: going for a ride?\" notification arrives; tap it."], place: .scooterHome),
        "c6b": CheckGuide(proves: "The notification plays the Kick-off chime you chose.",
                          steps: ["Ringer switch ON (not silent), volume up.",
                                  "iPhone Settings → Notifications → CorckieApp → Sounds ON (Developer → Permissions shows it).",
                                  "Do the c6 steps.",
                                  "Did you hear the Kick-off chime with the notification?", "Tap Pass or Fail."], place: .scooterHome),
        "c7": CheckGuide(proves: "The wake-up and recording also work in Low Power Mode.",
                         steps: ["Turn Low Power Mode on (Control Centre or Settings → Battery).", "Scooter off; app in the background; lock the phone.",
                                 "Switch the scooter on and walk for ~1 minute.", "Unlock and look; then turn Low Power Mode off if you like."], place: .scooterHome),
        "c8": CheckGuide(proves: "A whole ride records with the phone locked: no data gaps, and how much phone battery it costs.",
                         steps: ["Before riding: Developer → Sensors → Start recording.", "Lock the phone and ride 20+ minutes.",
                                 "After the ride: Sensors → Stop recording."], place: .ride),
        "d1": CheckGuide(proves: "The fake scooter replays your real ride 1 with the right numbers.",
                         steps: ["Run all automatic, or: Simulated scooter → Ride 1 · 50× · No fault → Start."], place: .noScooter),
        "d2": CheckGuide(proves: "The app can write to the backup folder you picked.",
                         steps: ["Developer → Backup folder → Pick folder (e.g. iCloud Drive › CorckieApp).", "Write test file."], place: .noScooter),
        "d3": CheckGuide(proves: "The backup folder still works after a phone restart.",
                         steps: ["Restart the phone.", "Developer → Backup folder → Write test file."], place: .noScooter),
        "d4": CheckGuide(proves: "The app notices when it crashed.",
                         steps: ["Developer → Crash catcher → Crash the app now.", "Open the app again."], place: .noScooter),
        "d5": CheckGuide(proves: "iOS's own crash reports reach the app.",
                         steps: ["Arrives by itself up to a day after d4."], place: .passive),
        "d6": CheckGuide(proves: "Errors are stored in the database for the export.",
                         steps: ["Run all automatic, or: Crash catcher → Write a test entry."], place: .noScooter),
        "d7": CheckGuide(proves: "When the scooter drops mid-ride, the phone takes over (GPS speed) and totals stay scooter-only.",
                         steps: ["Run all automatic, or: Simulated scooter → Fault \"D7 · Disconnect at 40%\" → 50× → Start."], place: .noScooter),
        "d8": CheckGuide(proves: "Simulated rides never touch your real data.",
                         steps: ["Checked after every simulator run (Run all automatic does one)."], place: .noScooter),
        "d9": CheckGuide(proves: "A backup can be restored with every row intact.",
                         steps: ["Run all automatic, or: Backup folder → Test backup + restore."], place: .noScooter),
        "e1": CheckGuide(proves: "The fuel price setting is ready (manual in v1).",
                         steps: ["Nothing to do. Change it in Settings → Fuel price."], place: .noScooter),
        "e2": CheckGuide(proves: "Holidays download from Hebcal.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e3": CheckGuide(proves: "The weather forecast downloads.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e3b": CheckGuide(proves: "The forecast works for your real area, not a test point.",
                          steps: ["Location allowed (h1).", "Run all automatic (with internet)."], place: .noScooter),
        "e4": CheckGuide(proves: "The backup forecast (MET Norway) downloads.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e5": CheckGuide(proves: "Yesterday's weather downloads (for ride factors).", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e6": CheckGuide(proves: "Map elevation downloads.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e6b": CheckGuide(proves: "Elevation works for your real area.", steps: ["Location allowed (h1).", "Run all automatic (with internet)."], place: .noScooter),
        "e7": CheckGuide(proves: "Map tiles for Ride Replay download.", steps: ["Run all automatic (with internet)."], place: .noScooter),
        "e8": CheckGuide(proves: "With no internet every source falls back calmly.",
                         steps: ["Turn airplane mode on.", "Developer → Outside data → Run all (~20 s).", "Turn airplane mode off."], place: .noScooter),
        "f1": CheckGuide(proves: "The barometer sees the arch bridge as a climb.", steps: ["Done (your verdict, 4 Oct)."], place: .ride),
        "f2": CheckGuide(proves: "The live numbers are readable on the handlebar mount.",
                         steps: ["Developer → Readability → Normal, phone on the mount.", "Tap Pass or Fail."], place: .ride),
        "f3": CheckGuide(proves: "The sunlight style is readable in direct sun.",
                         steps: ["Readability → Sunlight, in direct sun.", "Tap Pass or Fail."], place: .ride),
        "g1": CheckGuide(proves: "Everything reaches Claude in one file.",
                         steps: ["Developer → Results → Prepare export → Share → send to Claude."], place: .noScooter)
    ]
}
